<a href="https://colab.research.google.com/github/AishwaryaHoysal24/PyTorch-Zero-to-GANs/blob/Main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In PyTorch, a tensor is a multi-dimensional array that is the fundamental building block for data and computations. It is similar to a NumPy array, but with the added advantage of being able to run on GPUs for accelerated computations.

**Key Points:**
- Multi-dimensional:
Tensors can represent data in any number of dimensions, from a 0-D scalar to a 1-D vector, 2-D matrix, and beyond.

- Homogeneous data type:
All elements within a tensor must have the same data type, such as float32, int64, etc.

- GPU support:
PyTorch tensors can seamlessly move between CPU and GPU memory, enabling efficient computation on GPUs.

- Optimized operations:
PyTorch provides a wide range of optimized operations for manipulating and performing computations on tensors, including mathematical operations, linear algebra, and more.

**Common Use Cases:**
- Storing data:
Tensors are used to store input data, model parameters, and intermediate results during deep learning computations.

- Building neural networks:
Tensors are the core data structure used to define and manipulate neural network layers and operations.

- Performing computations:
PyTorch provides efficient tensor operations for performing computations such as matrix multiplication, convolutions, and more.

In [1]:
import torch

In [2]:
#Numbers
t1=torch.tensor(4.0)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t1.shape

torch.Size([])

In [6]:
#vectors
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [8]:
t2.dtype

torch.float32

In [9]:
t2.shape

torch.Size([4])

In [14]:
#Matrix
t3=torch.tensor([[5.,6],[7,8],[9,10]])
t3
#All the numbers will have same type

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [11]:
t3.dtype

torch.float32

In [12]:
t3.shape

torch.Size([3, 2])

In [15]:
#3D Matrix
t4=torch.tensor([[[11,12,13],[13,14,15]],[[15,16,17],[17,18,19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [16]:
t4.dtype

torch.float32

In [17]:
t4.shape # Go outside-in to fig out the shape

torch.Size([2, 2, 3])

In [18]:
#Tensor can never exist in improper shapes
t5=torch.tensor([[5.,6,11],[7,8],[9,10]])
t5

ValueError: expected sequence of length 3 at dim 1 (got 2)

In [19]:
#Tensor Operations and gradient
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [20]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [22]:
#compute derivative (refered in vector,matrices,derivatives)
y.backward()

In [23]:
#Display gradients
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [24]:
#Tensor Functions
t6=torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [25]:
t7=torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [26]:
t8=torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [27]:
t9=t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [28]:
#Interoperability with Numpy

In [29]:
import numpy as np
x=np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [30]:
# convert numpy-->tensor
y=torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [31]:
x.dtype ,y.dtype

(dtype('float64'), torch.float64)

In [32]:
#convert tensor-->numpy
z=y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [33]:
#Why we need PyTorch?
# - Autograd :create gradients.
# - GPU capability

In [34]:
!pip install jovian --upgrade --quiet

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 1.9 MB/s eta 0:00:00


In [35]:
import jovian

In [36]:
jovian.commit(project='PyTorch-Basics')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
